ezgripper_dual_gen2_triple_mount:

  ezgripper_controller:
    type: position_controllers/GripperActionController
    joint: left1_ezgripper_knuckle_palm_L1_1
    max_effort: 1.0

  gazebo_ros_control:
    pid_gains:
      left1_ezgripper_knuckle_palm_L1_1: {p: 100.0, i: 0.01, d: 10.0}