ezgripper_controller:

    port: /dev/ttyUSB0
    baudrate: 57600

    no_of_grippers: 1

    gripper_1:
      action_name: gripper_cmd
      servo_ids: [1]
      module_type: dual_gen1
      robot_ns: ezgripper_dual_gen1 # namespace of the robot
