ezgripper_controller:

    port: /dev/ttyUSB0
    baudrate: 57600

    no_of_grippers: 1

    gripper_1:
      action_name: gripper_cmd
      servo_ids: [1]
      robot_ns: ezgripper_single_mount # namespace of the robot
