ezgripper_dual_gen2_triple_mount:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  ezgripper_controller:
    type: position_controllers/GripperActionController
    joint: left1_ezgripper_knuckle_palm_L1_1
    max_effort: 1.0

gazebo_ros_control:
  pid_gains:
    left1_ezgripper_knuckle_palm_L1_1: {p: 100.0, i: 0.01, d: 10.0}
    left1_ezgripper_knuckle_palm_L1_2: {p: 100.0, i: 0.01, d: 10.0}
    left2_ezgripper_knuckle_palm_L1_1: {p: 100.0, i: 0.01, d: 10.0}
    left2_ezgripper_knuckle_palm_L1_2: {p: 100.0, i: 0.01, d: 10.0}
    left3_ezgripper_knuckle_palm_L1_1: {p: 100.0, i: 0.01, d: 10.0}
    left3_ezgripper_knuckle_palm_L1_2: {p: 100.0, i: 0.01, d: 10.0}

controller_list:
  - name: ezgripper_dual_gen2_triple_mount/ezgripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    max_effort: 1.0
    joints:
      - left1_ezgripper_knuckle_palm_L1_1