#!/usr/bin/env bash

rostopic pub /ezgripper_single_mount/ezgripper_controller/gripper_cmd/goal \
  control_msgs/GripperCommandActionGoal \
    "goal: {command: {position: -1.5707, max_effort: 1.0}}" -1 # -1 is to publish and latch for 3.0s
