ezgripper_quad:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  ezgripper_controller:
    type: position_controllers/GripperActionController
    joint: left_ezgripper_knuckle_1
    max_effort: 1.0

gazebo_ros_control:
  pid_gains:
    left_ezgripper_knuckle_1: {p: 100.0, i: 0.01, d: 10.0}
    left_ezgripper_knuckle_2: {p: 100.0, i: 0.01, d: 10.0}
    left_ezgripper_knuckle_3: {p: 100.0, i: 0.01, d: 10.0}
    left_ezgripper_knuckle_4: {p: 100.0, i: 0.01, d: 10.0}

controller_list:
  - name: ezgripper_quad/ezgripper_controller
    action_ns: gripper_cmd
    type: GripperCommand
    max_effort: 1.0
    joints:
      - left_ezgripper_knuckle_1